project_id = "rqpgexsonigkrwhdlznm"

[functions.bling-oauth-callback]
verify_jwt = false

[functions.bling-check-connection]
verify_jwt = false

[functions.bling-sync-products]
verify_jwt = false

[functions.bling-create-order]
verify_jwt = false
